development:
  adapter: postgresql
  encoding: unicode
  database: morphic_dev
  pool: 5
  username: <%= ENV["dev_db_username"] %>
  password: <%= ENV["dev_db_password"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: morphic_test
  pool: 5
  username: <%= ENV["dev_db_username"] %>
  password: <%= ENV["dev_db_password"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: morphic_prod
  pool: 5
  username: <%= ENV["dev_db_username"] %>
  password: <%= ENV["dev_db_password"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
